CREATE TABLE `cali_2022` (
  `activity_year` int DEFAULT NULL,
  `derived_msa_md` int DEFAULT NULL,
  `state_code` text,
  `county_code` text,
  `census_tract` text,
  `loan_type` int DEFAULT NULL,
  `loan_purpose` int DEFAULT NULL,
  `lien_status` int DEFAULT NULL,
  `loan_amount` double DEFAULT NULL,
  `loan_to_value_ratio` double DEFAULT NULL,
  `interest_rate` double DEFAULT NULL,
  `action_taken` int DEFAULT NULL,
  `purchaser_type` int DEFAULT NULL,
  `preapproval` int DEFAULT NULL,
  `property_value` int DEFAULT NULL,
  `total_units` int DEFAULT NULL,
  `occupancy_type` int DEFAULT NULL,
  `construction_method` int DEFAULT NULL,
  `income` int DEFAULT NULL,
  `debt_to_income_ratio` text,
  `applicant_credit_score_type` int DEFAULT NULL,
  `applicant_age` text,
  `applicant_sex` int DEFAULT NULL,
  `applicant_race_1` int DEFAULT NULL,
  `applicant_ethnicity_1` int DEFAULT NULL,
  `tract_population` int DEFAULT NULL,
  `tract_minority_population_percent` double DEFAULT NULL,
  `ffiec_msa_md_median_family_income` int DEFAULT NULL,
  `tract_to_msa_income_percentage` double DEFAULT NULL,
  `tract_owner_occupied_units` int DEFAULT NULL,
  `tract_one_to_four_family_homes` int DEFAULT NULL,
  `tract_median_age_of_housing_units` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
